@startuml
class Person {
  +name: String
  -age: Int
  #address: String
  +greet(): void
}

class Student {
  +module: String
}

class Address {
  +address: String
}

interface Speakable {
  +speak(): void
}
enum Gender {
  MALE
  FEMALE
}

Person <|-- Student
Person o-- "1..*" Address
@enduml
